import os

import pandas as pd

BASE_PATH = './UNITED_DATASET/'
INPUT_FOLDER = os.path.join(BASE_PATH, 'EXPERIMENT/')
INPUT_FOLDER_CENTERS = os.path.join(BASE_PATH, 'CENTERS/')
PARAMS_FILE = os.path.join(BASE_PATH, 'thresh_params.csv')
DF_PARAMS = pd.read_csv(PARAMS_FILE, index_col=0)


AXIS_FONT_SIZE = 16
AXIS_TICK_SIZE = 12
LEGEND_TITLE_FONT_SIZE = 14
LEGEND_TEXT_FONT_SIZE = 12
DISTANCE_LEGEND_TITLE = 'Distance from\nCHX (cm)'
colors = ['#9ECAE1', '#4292C6', '#084594', '#969696']
RED = (255, 0, 0)
WHITE = (255, 255, 255)
PLOT_WIDTH = 5
ELLIPSE_LINE_WIDTH = 8
